import fs from "fs";
import axios from "axios";
import FormData from "form-data";
import prisma from "../../../prisma/client.js";
import { envVars } from "../../../config/env.js";
import { VapiLib } from "../../../lib/vapi.js";
import { parseMenuFile } from "../../../utils/menuParser.js";
import { SubscriptionService } from "../../businessowner/subscription/subscription.service.js";
import DevBuildError from "../../../lib/DevBuildError.js";
import { StatusCodes } from "http-status-codes";

const createAgent = async (
  agentName,
  rulesFile,
  menuFile,
  businessId,
  userId,
) => {
  // 1. Verify the business exists
  const business = await prisma.business.findUnique({
    where: { id: businessId },
  });

  if (!business) {
    throw new DevBuildError("Business not found", StatusCodes.NOT_FOUND);
  }

  // Enforce plan limits check
  const limits = await SubscriptionService.checkPlanLimits(businessId);
  if (limits.isExceeded) {
    throw new DevBuildError(limits.reason, StatusCodes.PAYMENT_REQUIRED);
  }

  // 2. Prepare form data to forward to the AI Service
  const formData = new FormData();

  formData.append("business_id", agentName);

  if (rulesFile) {
    formData.append("rules_file", fs.createReadStream(rulesFile.path), {
      filename: rulesFile.originalname,
      contentType: rulesFile.mimetype,
    });
  }

  if (menuFile) {
    formData.append("menu_file", fs.createReadStream(menuFile.path), {
      filename: menuFile.originalname,
      contentType: menuFile.mimetype,
    });
  }

  try {
    // 3. Hit the AI Team's endpoint
    const aiEndpoint = `${envVars.AI_SERVICE_URL}/api/agents/create`;
    console.log(
      `Forwarding agent creation [${agentName}] for business [${businessId}]`,
    );

    const aiServiceResponse = await axios.post(aiEndpoint, formData, {
      headers: {
        ...formData.getHeaders(),
      },
      maxContentLength: Infinity,
      maxBodyLength: Infinity,
    });

    const aiData = aiServiceResponse.data;

    // 4. Store data in database
    const result = await prisma.$transaction(async (tx) => {
      // Create a new Agent record
      const agent = await tx.agent.create({
        data: {
          businessId: businessId,
          name: agentName,
          vapiAgentId: aiData.assistant_id || aiData.id || "N/A",
          script:
            aiData.vapi_response?.model?.messages?.[0]?.content ||
            aiData.script ||
            "Generated by AI Service",
          status: "active",
          twilioNumber: "TBD",
          managerNumber: "TBD",
        },
      });

      // Create Training Session
      const session = await tx.trainingSession.create({
        data: {
          businessId: businessId,
          agentId: agent.id,
          createdBy: userId,
          type: "voice",
          status: "completed",
        },
      });

      // 5. Record Training Files
      const trainingFiles = [];
      if (rulesFile) {
        trainingFiles.push({
          sessionId: session.id,
          fileName: rulesFile.originalname,
          fileUrl: rulesFile.path,
          fileType: "rules",
        });
      }
      if (menuFile) {
        trainingFiles.push({
          sessionId: session.id,
          fileName: menuFile.originalname,
          fileUrl: menuFile.path,
          fileType: "menu",
        });

        // Parse and populate Items table
        try {
          const parsedItems = await parseMenuFile(menuFile.path);
          if (parsedItems && parsedItems.length > 0) {
            const existingItems = await tx.item.findMany({
              where: {
                businessId: businessId,
                vapiAgentId: agent.vapiAgentId,
              },
              include: { orderItems: true },
            });

            const parsedKeys = new Set();

            for (const item of parsedItems) {
              const normalizedName = item.name.trim().toLowerCase();
              const normalizedCategory = item.category.trim().toLowerCase();
              const uniqueKey = `${normalizedName}||${normalizedCategory}`;
              parsedKeys.add(uniqueKey);

              const match = existingItems.find(
                (existing) =>
                  existing.name.trim().toLowerCase() === normalizedName &&
                  existing.category.trim().toLowerCase() === normalizedCategory,
              );

              if (match) {
                await tx.item.update({
                  where: { id: match.id },
                  data: {
                    unit: item.unit,
                    price: Number(item.price),
                    vapiAgentId: agent.vapiAgentId,
                  },
                });
              } else {
                await tx.item.create({
                  data: {
                    businessId: businessId,
                    category: item.category,
                    name: item.name,
                    unit: item.unit,
                    price: Number(item.price),
                    vapiAgentId: agent.vapiAgentId,
                  },
                });
              }
            }

            for (const existing of existingItems) {
              const existingKey = `${existing.name.trim().toLowerCase()}||${existing.category.trim().toLowerCase()}`;
              if (!parsedKeys.has(existingKey)) {
                if (existing.orderItems.length === 0) {
                  await tx.item.delete({
                    where: { id: existing.id },
                  });
                } else {
                  console.log(
                    `ℹ️ Menu Sync: Preserving item "${existing.name}" (ID: ${existing.id}) as it is referenced in past orders.`,
                  );
                }
              }
            }

            console.log(
              `Successfully updated and synced ${parsedItems.length} menu items for agent ${agent.name}.`,
            );
          }
        } catch (parseError) {
          console.error("❌ Error parsing/saving menu file items:", parseError);
          throw new Error(
            `Failed to parse the uploaded menu file: ${parseError.message}`,
          );
        }
      }


      await tx.trainingFile.createMany({
        data: trainingFiles,
      });

      return { agent, session, aiResponse: aiData };
    });

    return result;
  } catch (error) {
    console.error("AI Service Error:", error.response?.data || error.message);
    throw new Error(
      `Failed to create agent via AI Service: ${error.response?.data?.message || error.message}`,
    );
  }
};

const getAgents = async (businessId) => {
  const whereClause = businessId ? { businessId } : {};

  const agents = await prisma.agent.findMany({
    where: whereClause,
    select: {
      id: true,
      businessId: true,
      name: true,
      twilioNumber: true,
      managerNumber: true,
      status: true,
      vapiAgentId: true,
    },
  });

  return agents;
};

const deleteAgent = async (agentId) => {
  const agent = await prisma.agent.findFirst({
    where: {
      OR: [{ id: agentId }, { vapiAgentId: agentId }],
    },
  });

  if (!agent) {
    throw new Error("Agent not found");
  }

  // Delete the assistant from Vapi if vapiAgentId is registered
  if (agent.vapiAgentId && agent.vapiAgentId !== "N/A") {
    try {
      console.log(`Deleting Vapi Assistant: ${agent.vapiAgentId}`);
      await VapiLib.deleteAssistant(agent.vapiAgentId);
    } catch (err) {
      console.error(
        `Failed to delete assistant ${agent.vapiAgentId} from Vapi:`,
        err.message,
      );
    }
  }

  return await prisma.$transaction(async (tx) => {
    // A. Delete Training Files
    await tx.trainingFile.deleteMany({
      where: {
        session: {
          agentId: agent.id,
        },
      },
    });

    // B. Delete Training Sessions
    await tx.trainingSession.deleteMany({
      where: { agentId: agent.id },
    });

    // C. Cascade Delete items associated with the agent's vapiAgentId
    if (agent.vapiAgentId) {
      const items = await tx.item.findMany({
        where: { vapiAgentId: agent.vapiAgentId },
      });
      const itemIds = items.map((item) => item.id);

      if (itemIds.length > 0) {
        await tx.orderItem.deleteMany({
          where: { itemId: { in: itemIds } },
        });

        await tx.item.deleteMany({
          where: { id: { in: itemIds } },
        });
      }
    }

    // D. Delete the Agent record
    await tx.agent.delete({
      where: { id: agent.id },
    });

    return { success: true };
  });
};

const updateSpecialOffers = async (agentId, enabled) => {
  const agent = await prisma.agent.findFirst({
    where: {
      OR: [{ id: agentId }, { vapiAgentId: agentId }],
    },
  });

  if (!agent) {
    throw new Error("Agent not found");
  }

  try {
    const aiEndpoint = `${envVars.AI_SERVICE_URL}/api/agents/${agent.name}/special-offers`;
    console.log(
      `Updating special offers for agent [${agent.name}] to enabled: ${enabled}`,
    );

    const aiServiceResponse = await axios.patch(aiEndpoint, {
      enabled: enabled,
    });

    const aiData = aiServiceResponse.data;

    const updatedScript =
      aiData.vapi_response?.model?.messages?.[0]?.content || aiData.script;

    let updatedAgent = agent;
    if (updatedScript) {
      updatedAgent = await prisma.agent.update({
        where: { id: agent.id },
        data: {
          script: updatedScript,
        },
      });
    }

    return { agent: updatedAgent, aiResponse: aiData };
  } catch (error) {
    console.error("AI Service Error:", error.response?.data || error.message);
    throw new Error(
      `Failed to update agent special offers via AI Service: ${error.response?.data?.message || error.message}`,
    );
  }
};

const uploadSpecialOffers = async (
  agentIdOrAssistantId,
  specialOffersFile,
  specialOffersText,
  specialOffersEnabled,
) => {
  const agent = await prisma.agent.findFirst({
    where: {
      OR: [{ id: agentIdOrAssistantId }, { vapiAgentId: agentIdOrAssistantId }],
    },
  });

  if (!agent) {
    throw new DevBuildError("Agent not found", StatusCodes.NOT_FOUND);
  }

  const assistantId = agent.vapiAgentId || agentIdOrAssistantId;

  const formData = new FormData();
  formData.append("assistant_id", assistantId);

  if (specialOffersFile) {
    formData.append(
      "special_offers_file",
      fs.createReadStream(specialOffersFile.path),
      {
        filename: specialOffersFile.originalname,
        contentType: specialOffersFile.mimetype,
      },
    );
  }

  if (specialOffersText !== undefined && specialOffersText !== null) {
    formData.append("special_offers_text", String(specialOffersText));
  }

  if (specialOffersEnabled !== undefined && specialOffersEnabled !== null) {
    formData.append("special_offers_enabled", String(specialOffersEnabled));
  }

  try {
    const aiEndpoint = `${envVars.AI_SERVICE_URL}/api/agents/upload-special-offers`;
    console.log(
      `Forwarding special offers upload for assistant [${assistantId}]`,
    );

    const aiServiceResponse = await axios.post(aiEndpoint, formData, {
      headers: {
        ...formData.getHeaders(),
      },
      maxContentLength: Infinity,
      maxBodyLength: Infinity,
    });

    const aiData = aiServiceResponse.data;

    const updatedScript =
      aiData.vapi_response?.model?.messages?.[0]?.content || aiData.script;

    let updatedAgent = agent;
    if (updatedScript) {
      updatedAgent = await prisma.agent.update({
        where: { id: agent.id },
        data: {
          script: updatedScript,
        },
      });
    }

    if (specialOffersFile) {
      const session = await prisma.trainingSession.findFirst({
        where: { agentId: agent.id },
        orderBy: { createdAt: "desc" },
      });

      if (session) {
        await prisma.trainingFile.create({
          data: {
            sessionId: session.id,
            fileName: specialOffersFile.originalname,
            fileUrl: specialOffersFile.path,
            fileType: "special_offers",
          },
        });
      }
    }

    return { agent: updatedAgent, aiResponse: aiData };
  } catch (error) {
    console.error("AI Service Error:", error.response?.data || error.message);
    throw new Error(
      `Failed to upload special offers via AI Service: ${error.response?.data?.message || error.message}`,
    );
  }
};

export const AIAgentService = {
  createAgent,
  getAgents,
  deleteAgent,
  updateSpecialOffers,
  uploadSpecialOffers,
};
